### ISSUE TITLE
I can't see game chapters

### ISSUE THREAD

**Issue by brahim024** [parsariyahi/progature#12]
![progature](https://github.com/parsariyahi/progature/assets/60741749/14e04ae9-129d-4a48-89b7-02f17b65ac7c)

**Comment by parsariyahi** [comment]
can you provide me more info about your operating system, maybe reason is the games won't load, and see ``/db/games/`` dir

**Comment by parsariyahi** [comment]
fixed on #13 pr

**Comment by brahim024** [comment]
@parsariyahi ok I'll check
